# Generated by Django 4.2.4 on 2024-01-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_historical_data_v3',
            name='Stock_Historical_Data_V3_Quarter',
            field=models.IntegerField(blank=True, default=11),
        ),
        migrations.AlterField(
            model_name='stock_historical_data_v3',
            name='Stock_Historical_Data_V3_FilingDate',
            field=models.CharField(max_length=30),
        ),
    ]
