# Generated by Django 4.2.4 on 2024-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next_filing_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Next_Filing_Dates_Column1', models.IntegerField()),
                ('Next_Filing_Dates_StockID', models.IntegerField()),
                ('Next_Filing_Dates_Avg_Diff', models.IntegerField()),
                ('Next_Filing_Dates_DateDifference', models.IntegerField()),
                ('Next_Filing_Dates_FiscalQuarter', models.IntegerField()),
                ('Next_Filing_Dates_FiscalQuarterEnd', models.CharField(max_length=30)),
                ('Next_Filing_Dates_Next_FD', models.CharField(max_length=30)),
                ('Next_Filing_Dates_Remaining_Days', models.IntegerField()),
                ('Next_Filing_Dates_Avg_EEPS', models.FloatField()),
                ('Next_Filing_Dates_Avg_FEPS', models.FloatField()),
                ('Next_Filing_Dates_Next_Actual_EPS', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Details_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Details_Symbol', models.CharField(max_length=30)),
                ('Stock_Details_Name', models.CharField(max_length=30)),
                ('Stock_Details_Description', models.TextField(max_length=250)),
                ('Stock_Details_Country', models.CharField(max_length=30)),
                ('Stock_Details_State', models.CharField(max_length=30)),
                ('Stock_Details_StockID', models.IntegerField()),
                ('Stock_Details_Sector', models.CharField(max_length=30)),
                ('Stock_Details_Industry', models.CharField(max_length=30)),
                ('Stock_Details_Total_Revenue', models.CharField(max_length=30)),
                ('Stock_Details_NAICS_Code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Earnings_Date', models.CharField(max_length=30)),
                ('Stock_Earnings_Estimated_EPS', models.FloatField()),
                ('Stock_Earnings_Actual_EPS', models.FloatField()),
                ('Stock_Earnings_StockID', models.IntegerField()),
                ('Stock_Earnings_Surprise', models.FloatField()),
                ('Stock_Earnings_End_of_Quarter', models.CharField(max_length=30)),
                ('Stock_Earnings_EPS_Estimate_isNull', models.IntegerField()),
                ('Stock_Earnings_Reported_EPS_isNull', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_historical_data_v3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Historical_Data_V3_Column1', models.IntegerField()),
                ('Stock_Historical_Data_V3_Year', models.IntegerField()),
                ('Stock_Historical_Data_V3_StockID', models.IntegerField()),
                ('Stock_Historical_Data_V3_FilingDate', models.IntegerField()),
                ('Stock_Historical_Data_V3_FiscalQuarterEnd', models.CharField(max_length=30)),
                ('Stock_Historical_Data_V3_FQE_10', models.CharField(max_length=30)),
                ('Stock_Historical_Data_V3_Price_Next_Day', models.FloatField()),
                ('Stock_Historical_Data_V3_Previous_Price', models.FloatField()),
                ('Stock_Historical_Data_V3_Impact', models.FloatField()),
                ('Stock_Historical_Data_V3_Impact_2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Naics_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Naics_Column1', models.CharField(max_length=30)),
                ('Stock_Naics_Level', models.IntegerField()),
                ('Stock_Naics_Hierarchical_structure', models.CharField(max_length=30)),
                ('Stock_Naics_Code', models.IntegerField()),
                ('Stock_Naics_Parent', models.IntegerField()),
                ('Stock_Naics_Class_title', models.TextField(max_length=250)),
                ('Stock_Naics_Superscript', models.CharField(max_length=30)),
                ('Stock_Naics_Class_definition', models.CharField(max_length=30)),
                ('Stock_Naics_symbol', models.CharField(max_length=30)),
                ('Stock_Naics_StockID', models.IntegerField()),
            ],
        ),
    ]
