# Generated by Django 4.2.4 on 2024-01-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_filing_dates',
            name='Next_Filing_Dates_Next_Actual_EPS',
            field=models.CharField(max_length=30),
        ),
    ]
