# Generated by Django 4.2.4 on 2024-01-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0002_alter_next_filing_dates_next_filing_dates_next_actual_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_earnings_4',
            name='Stock_Earnings_4_Surprise',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_Class_definition',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_Class_title',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_Parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_Superscript',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_symbol',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
