# Generated by Django 4.2.4 on 2024-01-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0002_stock_historical_data_v3_stock_historical_data_v3_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_filing_dates',
            name='Next_Filing_Dates_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id'),
        ),
        migrations.AlterField(
            model_name='stock_earnings',
            name='Stock_Earnings_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id'),
        ),
    ]
