# Generated by Django 4.2.4 on 2024-01-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0003_alter_next_filing_dates_next_filing_dates_stockid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_details_table',
            name='Stock_Details_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id', unique=True),
        ),
    ]
