# Generated by Django 4.2.4 on 2024-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0003_alter_stock_earnings_4_stock_earnings_4_surprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_Class_definition',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
