# Generated by Django 4.2.4 on 2024-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0004_alter_stock_naics_table_stock_naics_class_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T3_Index', models.CharField(max_length=30)),
                ('Correlation_Coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EQ_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=30)),
                ('Value', models.FloatField()),
                ('Sum_of_StockValue', models.FloatField()),
                ('Index', models.CharField(max_length=30)),
                ('Symbol', models.CharField(max_length=30)),
                ('Quarters', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Variable_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variables_VariableID', models.IntegerField()),
                ('Variables_VariableName', models.CharField(max_length=30)),
                ('Variables_VariableShort', models.CharField(max_length=30)),
            ],
        ),
    ]
