# Generated by Django 4.2.4 on 2024-01-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0004_alter_stock_details_table_stock_details_stockid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_id',
            name='stock_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
