# Generated by Django 4.2.4 on 2024-01-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0005_alter_stock_id_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_filing_dates',
            name='Next_Filing_Dates_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id'),
        ),
        migrations.AlterField(
            model_name='stock_earnings',
            name='Stock_Earnings_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id'),
        ),
        migrations.AlterField(
            model_name='stock_historical_data_v3',
            name='Stock_Historical_Data_V3_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id'),
        ),
        migrations.AlterField(
            model_name='stock_naics_table',
            name='Stock_Naics_StockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id'),
        ),
    ]
