# Generated by Django 4.2.4 on 2024-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0005_correlation_values_eq_table_variable_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Correlation_values',
            new_name='Correlation_value',
        ),
    ]
