# Generated by Django 4.2.4 on 2024-02-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0006_rename_correlation_values_correlation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T3_Index', models.CharField(max_length=30)),
                ('Correlation_Coefficient', models.FloatField()),
                ('Correlation_stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stock_id', to_field='stock_id')),
            ],
        ),
        migrations.DeleteModel(
            name='Correlation_value',
        ),
    ]
